### ISSUE TITLE
serval issue with vs

### ISSUE THREAD

**Issue by liquidzym** [igiso/ofxTextField#1]
wc.lpszClassName = g_szClassName;
can't covert “const LPCSTR” to “LPCWSTR”
and 
error C2065: “pointerToWindow”: undeclared identifier

**Comment by igiso** [comment]
mac or pc?

**Comment by liquidzym** [comment]
pc with vs2013

**Comment by igiso** [comment]
I ll be right back at you ,

**Comment by igiso** [comment]
changing     pointerToWindow = NULL;

to

  #ifdef TARGET_OSX
    pointerToWindow = NULL;
    #endif

will do the job in Codeblocks,

I will try download VS and test it there as well

Thanks for the feedback!

**Comment by igiso** [comment]
@liquidzym
Can You give it a go with the current version?

I've fixed the other issues as well!

**Comment by liquidzym** [comment]
ok，that's fine now,thanks for the fast reply
btw,the _WNDCLASSEXW wc; should be WNDCLASSEXW wc isn't it?  without underscore

**Comment by igiso** [comment]
yeah not sure what happened there, that's a typo
